### ISSUE TITLE
 Unable to Interact with zkapp Contract Despite Successful Deployment

### ISSUE THREAD

**Issue by PashaKlybik** [o1-labs/snarkyjs#1101]
Hello,

I've been encountering a persistent issue when attempting to interact with my zkapp contract. Even though the contract seems to be correctly deployed on the network (verified on Minascan and through the fetchAccount method), I'm consistently receiving the following errors:

We can't find this zkapp account in the ledger.
Because the zkapp account was not found in the cache. Try calling await fetchAccount(zkappAddress) first.
To ascertain my contract's presence on the network, I:

Checked its existence on Minascan and can confirm it's listed there.
Utilized the fetchAccount method with my zkapp contract's address, which returned relevant data .
`{
  publicKey: PublicKey {
    x: Field { value: [Array] },
    isOdd: Bool { value: [Array] }
  },
  tokenId: Field { value: [ 0, [Uint8Array] ] },
  tokenSymbol: '',
  balance: UInt64 { value: Field { value: [Array] } },
  nonce: UInt32 { value: Field { value: [Array] } },
  receiptChainHash: Field { value: [ 0, [Uint8Array] ] },
  delegate: PublicKey {
    x: Field { value: [Array] },
    isOdd: Bool { value: [Array] }
  },
  votingFor: Field { value: [ 0, [Uint8Array] ] },
  timing: {
    isTimed: Bool { value: [Array] },
    initialMinimumBalance: UInt64 { value: [Field] },
    cliffTime: UInt32 { value: [Field] },
    cliffAmount: UInt64 { value: [Field] },
    vestingPeriod: UInt32 { value: [Field] },
    vestingIncrement: UInt64 { value: [Field] }
  }, ...`
Given these verifications, I'm puzzled as to why I continue to face this error. I sought assistance from the community on Discord, but we couldn't pinpoint the root cause of the issue.

I'm reaching out here hoping for a deeper insight into this problem and any potential solutions or workarounds. Any guidance or advice would be immensely appreciated.

Thank you.

**Comment by mitschabaude** [comment]
This is not a known issue, so you'll have to provide way more info so that anyone can debug this! I assume that the account which can't be found and the account that you are checking on Minascan are different

**Comment by PashaKlybik** [comment]
Hello,

Thank you for the prompt response.

I assure you that the account I'm trying to interact with in my code and the one I'm checking on Minascan are the same. You can verify this using the following contract address on Minascan: https://minascan.io/testworld2/account/B62qk52dWhknKVrtb3dMMNKGJo6YjaTyfCFCacQN7YvfcaF7zwmEdoY/zkApp.

Regarding the method causing the error on line 75, here's a snippet for clarity:
https://github.com/zk-auth-com/mina-google-keys/blob/3dcd3d72023edce975f46b287dbba807fa364ee3/server/src/contract.ts#L35

If there's any other information or details you need from me to help debug this issue, please let me know. I'm eager to resolve this and continue with my development work.

Thank you for your assistance.

**Comment by mitschabaude** [comment]
Hey @PashaKlybik can you also post the stack trace? That would make it much easier to understand the error cause without cloning and running the code myself

**Comment by PashaKlybik** [comment]
@mitschabaude  
`contract compiled
contract created
create transaction 
Error: email.get() failed, either:
1. We can't find this zkapp account in the ledger
2. Because the zkapp account was not found in the cache. Try calling `await fetchAccount(zkappAddress)` first.
If none of these are the case, then please reach out on Discord at #zkapp-developers and/or open an issue to tell us!
    at file:///Users/pavelklybik/Documents/2023/bootstrap/mina-google-keys/contracts/node_modules/snarkyjs/dist/node/lib/state.js:154:27
    at Object.witness (snarkyjs/dist/node/lib/provable.js:165:28)
    at Object.get (snarkyjs/dist/node/lib/state.js:144:42)
    at MinaGoogleKeysContract.verifyAndSend (file:///Users/pavelklybik/Documents/2023/bootstrap/mina-google-keys/contracts/build/src/MinaGoogleKeysContract.js:51:41)
    at MinaGoogleKeysContract.wrappedMethod (snarkyjs/dist/node/lib/zkapp.js:177:41)
    at file:///Users/pavelklybik/Documents/2023/bootstrap/mina-google-keys/server/src/contract.ts:32:15
    at file:///Users/pavelklybik/Documents/2023/bootstrap/mina-google-keys/server/node_modules/.pnpm/snarkyjs@0.12.1/node_modules/snarkyjs/dist/node/lib/mina.js:79:25
    at Object.runUnchecked (snarkyjs@0.12.1/node_modules/snarkyjs/dist/node/lib/provable-context.js:50:20)
    at createTransaction (snarkyjs@0.12.1/node_modules/snarkyjs/dist/node/lib/mina.js:78:30)
    at Object.transaction (snarkyjs@0.12.1/node_modules/snarkyjs/dist/node/lib/mina.js:554:22)
    at Module.transaction (snarkyjs@0.12.1/node_modules/snarkyjs/dist/node/lib/mina.js:681:31)
    at sendTxs (file:///Users/pavelklybik/Documents/2023/bootstrap/mina-google-keys/server/src/contract.ts:28:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///Users/pavelklybik/Documents/2023/bootstrap/mina-google-keys/server/src/main.ts:8:16)`

**Comment by mitschabaude** [comment]
Thanks @PashaKlybik, I ended up debugging this in your repo. The problem is that you have two different versions of snarkyjs around, one in `/contracts` and one in `/server`. You do `Mina.setActiveInstance()` on the server version but then call `state.get()` (which uses the "Mina instance") in contract code -- so, when trying to get the state snarkyjs doesn't have the active instance set and in particular doesn't know the graphql API to fetch from.

It's bad that `state.get()` swallows tha actual error and throws something unhelpful in this edge case, I'll fix that.

In your repo, the error goes away if, from the `/server` code, you import snarkyjs like this:
```ts
import { Field, ... } from "../../contracts/node_modules/snarkyjs/dist/node/index.js";
```

**Comment by mitschabaude** [comment]
Btw, that's why the zkapp CLI makes snarkyjs a peer dependency and the docs tell you to use `npm link` from the contracts package - that way you don't get two different snarkyjs instances
