### ISSUE TITLE
Error when running some examples

### ISSUE THREAD

**Issue by themighty1** [o1-labs/snarkyjs#131]
Hi, on node v17.0.1, all examples work well except
./run src/examples/ex00_preimage.ts and
./run src/examples/ex01_small_preimage.ts

The error is:

generating keypair...
prove...
(PolyDivision)
wasm://wasm/0092e2ea:1

RuntimeError: unreachable
    at wasm://wasm/0092e2ea:wasm-function[667]:0x1c350b
    at wasm://wasm/0092e2ea:wasm-function[1660]:0x235a5d
    at wasm://wasm/0092e2ea:wasm-function[339]:0x124e49
    at Object.module.exports.caml_pasta_fp_plonk_proof_create (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/plonk_wasm.js:1133:20)
    at Object.m4 [as caml_pasta_fp_plonk_proof_create] (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:2338:5)
    at /home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:311585:33
    at caml_call4 (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:281446:16)
    at create_aux (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:311569:14)
    at create$1 (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:311583:14)
    at caml_call5 (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:267646:16)
    at create$2 (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:272275:14)
    at caml_call4 (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:799487:16)
    at _cP_ (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:801591:16)
    at caml_call1 (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:166370:28)
    at /home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:176348:27
    at caml_call2 (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:166372:28)
    at go (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:176321:18)
    at /home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:176320:22
    at am (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:491:39)
    at am (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:492:15)
    at /home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:497:62
    at am (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:490:32)
    at Object.am [as caml_call_gen] (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:492:15)
    at caml_call5 (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:799492:24)
    at prove (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:801597:16)
    at /home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:801688:38
    at am (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:491:39)
    at Function.<anonymous> (/home/default2/Desktop/poseidon/snarkyjs/dist/server/node_bindings/snarky_js_node.bc.js:1414:40)
    at Function.Class.<computed> [as prove] (/home/default2/Desktop/poseidon/snarkyjs/dist/server/index.js:53:52)
    at file:///home/default2/Desktop/poseidon/snarkyjs/src/examples/ex00_preimage.tmp.mjs:24:15

Node.js v17.0.1

**Comment by mitschabaude** [comment]
Hi @themighty1, this is an error that used to happen in an earlier version of snarkyjs. Could you check your version? It should work on 0.3.0, but is expected to fail on earlier versions

**Comment by themighty1** [comment]
Thanks @mitschabaude , mine is 0.2.2 - it's the version from the master branch. Is there a different repo with v0.3.0 ?

**Comment by mitschabaude** [comment]
There's no different repo :D Version 0.3.0 was published from a branch called `feature/deploy-txn`, which was subsequently split up into [multiple PRs](https://github.com/o1-labs/snarkyjs/pulls), which are currently being reviewed by the team and will be merged to the main branch within the next 1-2 weeks.

**Comment by themighty1** [comment]
Thanks for the heads up. Looking forward to the release. Im really impressed by how the code is well-organized and meticulously reviewed. Good work.

**Comment by themighty1** [comment]
Thanks, works with 0.3.1
