### ISSUE TITLE
Proving hash pre-image with > 1 Field Element

### ISSUE THREAD

**Issue by themighty1** [o1-labs/snarkyjs#143]
Hi, I was trying to modify ex00_preimage.ts to work with 2 Field elements.
Is > 1 Field element supported? I couldn't pass 2 elements to Main.Prove(), I was
getting an error:

```
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^
[
  0,
  [ 248, ai { t: 0, c: 'Js_of_ocaml__Js.Error', l: 21 }, 282 ],
  TypeError: typ.sizeInFields is not a function
      at /home/default2/Desktop/poseidon/snarkyjs/dist/server/index.js:741:50
      at Array.reduce (<anonymous>)
      at Object.sizeInFields (/home/default2/Desktop/poseidon/snarkyjs/dist/server/index.js:741:19)

```

Here's a minimal repro:

```
class Main extends Circuit {
  @circuitMain
  static main(preimage: Field[], @public_ hash: Field) {
    Poseidon.hash(preimage).assertEquals(hash);
  }
}

await isReady;
const kp = Main.generateKeypair();
const preimage = [Field.one, Field.one];
const hash = Poseidon.hash(preimage);
const pi = Main.prove(preimage, [hash], kp);
```

I would appreciate any pointers, thanks.

**Comment by mitschabaude** [comment]
To build complex private/public input shapes, you can extend `CircuitValue` and use the decorators `@prop` and `@arrayProp`:

```ts
await isReady;

class TwoFields extends CircuitValue {
  @arrayProp(Field, 2) fields: Field[];

  constructor(fields: Field[]) {
    super();
    this.fields = fields;
  }
}

class Main extends Circuit {
  @circuitMain
  static main(preimage: TwoFields, @public_ hash: Field) {
    Poseidon.hash(preimage.fields).assertEquals(hash);
  }
}

const kp = Main.generateKeypair();
const preimage = new TwoFields([Field.one, Field.one]);
const hash = Poseidon.hash(preimage.fields);
const pi = Main.prove([preimage], [hash], kp);
let ok = Main.verify([hash], kp.verificationKey(), pi);
console.log('ok?', ok);
```

**Comment by mitschabaude** [comment]
we should probably have a helper for "array of Fields / CircuitValues" that doesn't require writing out the CircuitValue class
