### ISSUE TITLE
Set `caller` fields correctly

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#431]
# Description
Given a zkApp `A` and a zkApp `B`, where `A` is calling a method on `B` and `B`'s method calls the `experimental.token` API, the callDepths of the returned AccountUpdates is wrong and fails on `apply_json_transaction` in OCaml.

# Example

## zkApp A
```ts
class Dex extends SmartContract {
  tokenX = ...; // Predefined static address

  @method supplyTokenX(user: PublicKey, dx: UInt64) {
    let tokenX = new TokenContract(this.tokenX);
    tokenX.transfer(user, this.address, dx);
  }
```

## zkAppB
```ts
class TokenContract extends SmartContract {
  @method transfer(from: PublicKey, to: PublicKey, value: UInt64) {
    this.experimental.token.send({ from, to, amount: value });
  }
```

```ts
tx = await Mina.transaction({ feePayerKey, fee: accountFee.mul(1) }, () => {
  dex.supplyTokenX(
    addresses.user, // Predefined static address
    UInt64.from(100_000),
  );
});
```

## Error
```
/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7565
         throw err;
         ^

Error: Unknown error thrown by raise
    at raise (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:89119:29)
    at ok_exn (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:89158:14)
    at apply_json_transaction (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:422097:34)
    at caml_call_gen (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:2081:17)
    at Object.applyJsonTransaction (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:3651:16)
    at Object.sendTransaction (file:///home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/lib/mina.js:179:24)
    at sendTransaction (file:///home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/lib/mina.js:482:27)
    at Object.send (file:///home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/lib/mina.js:115:20)
    at file:///home/martin/Code/o1/tools/dex/build/src/index.js:109:4
```

To fix this error, we can decrement the returned AccountUpdate structure such that each AccountUpdate's callDepth is decreased by `-1` and this passes the transaction logic in OCaml.

**Comment by MartinMinkov** [comment]
The returned AccountUpdate structure information looks like this:
```sh
-------------------------------------------------
FEE PAYER B62qocNf46Ha3uHaGL9dqts7RymUkp6NAdaeEJD1uREnQPktCEnBLzE
TOKEN X ADDRESS B62qiWSeSKfrQtNDK1NS8kWQx47XRU5vZpEiLsfLD7UCDLH129W2MLi
TOKEN Y ADDRESS B62qjhc4mVfJ7pivZBsXvazZF25NZdjdsyZXnGV7ky6BYQYhkgEXGUD
DEX ADDRESS B62qnC4nm3QGbACvTuMUeoL71Z3tJYHuJwjeFPaV9Gy8g7MHpEVSbsf
USER ADDRESS B62qn6zy1v1oXiKRmRcxVsq1g1d5K43XmbBAa6VEuhwiYxfY5zbuE1Q
-------------------------------------------------
```
```json
{
  "feePayer": {
    "body": {
      "publicKey": "B62qocNf46Ha3uHaGL9dqts7RymUkp6NAdaeEJD1uREnQPktCEnBLzE",
      "fee": "1000000000",
      "validUntil": null,
      "nonce": "8"
    },
    "authorization": "2Y9zLiaJWSGSjWaXRSPdRZJNgbZfZ8DMEtpD7FokBqhVfjDm1Vr891dsRBTVskN1R6mYH9UJ4jrPwzoRethJ6conKiZw4c2"
  },
  "accountUpdates": [
    {
      "body": {
        "publicKey": "B62qnC4nm3QGbACvTuMUeoL71Z3tJYHuJwjeFPaV9Gy8g7MHpEVSbsf",
        "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
        "balanceChange": { "magnitude": "0", "sgn": "Positive" },
        "incrementNonce": false,
        "events": [],
        "sequenceEvents": [],
        "callData": "27844747632040987822835044034241057360065235687377880862175908066088598750842",
        "callDepth": 0,
        "useFullCommitment": false,
        "caller": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf"
      },
      "authorization": { "proof": null, "signature": null }
    },
    {
      "body": {
        "publicKey": "B62qiWSeSKfrQtNDK1NS8kWQx47XRU5vZpEiLsfLD7UCDLH129W2MLi",
        "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
        "balanceChange": { "magnitude": "0", "sgn": "Positive" },
        "incrementNonce": false,
        "events": [],
        "sequenceEvents": [],
        "callData": "26326833007358166804286463660768160329913206018574041538454780538661343953593",
        "callDepth": 1,
        "useFullCommitment": false,
        "caller": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf"
      },
      "authorization": { "proof": null, "signature": null }
    },
    {
      "body": {
        "publicKey": "B62qn6zy1v1oXiKRmRcxVsq1g1d5K43XmbBAa6VEuhwiYxfY5zbuE1Q",
        "tokenId": "xyjpbF6zLnmgGXyNSRmvs3V3RapqJUswVajoH3azqYJtHZ24Pz",
        "balanceChange": { "magnitude": "100000", "sgn": "Negative" },
        "incrementNonce": false,
        "events": [],
        "sequenceEvents": [],
        "callData": "0",
        "callDepth": 2,
        "useFullCommitment": true,
        "caller": "xyjpbF6zLnmgGXyNSRmvs3V3RapqJUswVajoH3azqYJtHZ24Pz"
      },
      "authorization": {
        "proof": null,
        "signature": "2XycBckTPigeJWFxvDkQZr3SxpKUybx1eqzvds4RWg8qxdfhxdEdBVoHmkX3akvig2R6PHT1PcXHSraFoFReC3TGJ94kaeN"
      }
    },
    {
      "body": {
        "publicKey": "B62qnC4nm3QGbACvTuMUeoL71Z3tJYHuJwjeFPaV9Gy8g7MHpEVSbsf",
        "tokenId": "xyjpbF6zLnmgGXyNSRmvs3V3RapqJUswVajoH3azqYJtHZ24Pz",
        "balanceChange": { "magnitude": "100000", "sgn": "Positive" },
        "incrementNonce": false,
        "events": [],
        "sequenceEvents": [],
        "callData": "0",
        "callDepth": 2,
        "useFullCommitment": false,
        "caller": "xyjpbF6zLnmgGXyNSRmvs3V3RapqJUswVajoH3azqYJtHZ24Pz"
      },
      "authorization": { "proof": null, "signature": null }
    }
  ],
  "memo": "E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"
}
```

If we mutate the above JSON by decrementing each of the `callDepths` except the first AccountUpdate, the transaction passes.

```ts
tx.transaction.accountUpdates[1].body.callDepth -= 1;
tx.transaction.accountUpdates[2].body.callDepth -= 1;
tx.transaction.accountUpdates[3].body.callDepth -= 1;
```

**Comment by MartinMinkov** [comment]
With more debugging, it seems like only the second AccountUpdate needs to have its callDepth decremented. The second AccountUpdate is the one authorizing the third and fourth AccountUpdate to transfer with the token ID `xyjpbF6zLnmgGXyNSRmvs3V3RapqJUswVajoH3azqYJtHZ24Pz`

The other AccountUpdates can stay with a callDepth of `2` but the second one cannot be `1` it seems and needs to be `0`. Perhaps when we are checking token owner permissions, the callDepth must be `0`?

**Comment by MartinMinkov** [comment]
The error raised seems to be happening on this line: https://github.com/MinaProtocol/mina/blob/e4a75d6037b2fcf82fc3a873cd7baeedbb0adaae/src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml#L2969

**Comment by MartinMinkov** [comment]
More specifically, this assertion fails because `is_normal_call` is false

https://github.com/MinaProtocol/mina/blob/e4a75d6037b2fcf82fc3a873cd7baeedbb0adaae/src/lib/transaction_logic/zkapp_command_logic.ml#L894

**Comment by MartinMinkov** [comment]
This bug occurs because the `caller` field of the token contract is incorrect. By the `caller` field to the token id of its parent (which is the Dex), it will pass transaction logic.

**Comment by mitschabaude** [comment]
So it seems best to set the `caller` field in terms of  `Call` / `Delegate_call` as done by the protocol.

Proposed action plan:

* [ ] Implement the translation from `Call` / `Delegate_call` in JS, following https://github.com/MinaProtocol/mina/blob/d75a421ff620f704c78b23e45ee561250a705f5e/src/lib/mina_base/zkapp_command.ml#L614
* [ ] Make normal zkApp calls be `Delegate_call`
* [ ] Make the `experimental.token` functions be `Call`
* [ ] Enable some low-level way to make something a `Call`, to be used for now for the WIP token with proofs.
* [ ] Automatically figure out when a `Call` is needed (= when an account update has a custom token id) and eagerly modifies the first suitable ancestor to be `Call` (or throws an error if such ancestors don't exist). The question is, when should we do this figuring out? When creating the account update (probably not)? After all account updates are in place, just the transaction is finished (probably works)?
