### ISSUE TITLE
Dex: AccountUpdate.create causes error when using a different token id

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#449]
# Description
When calling `Account.create` with a different token id, the generated AccountUpdate structure fails. 

See this line here:
https://github.com/o1-labs/snarkyjs/blob/200be0ca0f575e08af2a62e1a3a001e7f53fd787/src/examples/zkapps/dex/dex.ts#L51

The following error is thrown:

```
Assert_failure,-11,0,src/lib/transaction_logic/zkapp_command_logic.ml,908,8
    at raise (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:89182:29)
    at ok_exn (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:89221:14)
    at apply_json_transaction (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:422183:34)
    at caml_call_gen (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:2081:17)
    at Object.applyJsonTransaction (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:3651:16)
    at Object.sendTransaction (file:///home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/lib/mina.js:179:24)
    at sendTransaction (file:///home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/lib/mina.js:482:27)
    at Object.send (file:///home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/lib/mina.js:115:20)
    at file:///home/martin/Code/o1/tools/dex/build/src/index.js:105:4
```

In the following generated structure, the 3rd account update seems to be the incorrect one.

```
-------------------------------------------------
FEE PAYER B62qk8LrxcgNw7cGxgrNT2zdRdXfiDrP977QixsFYAjsWExVfxSoqJV
TOKEN X ADDRESS B62qr9yya9KmQujHNTwdhE3tKeQXnxrVLkXqxU1ZusqiHCLok6cSDoa
TOKEN Y ADDRESS B62qmjsfVoMTgiKhG9VnVXT7Aj68iwULdy3GmpVpmbd9NZBnyFmwk9f
DEX ADDRESS B62qpRKsCw1ajngMUgPGi5baVkbCxpA8e6JTpRw5wiXf86CFs12GD2z
USER ADDRESS B62qjGfYeKAuuAnHR1AZZcZczFCff4g9WfgKF2cJcNS6tVS4JBUrsDr
-------------------------------------------------

```

```json
{
  "feePayer": {
    "body": {
      "publicKey": "B62qk8LrxcgNw7cGxgrNT2zdRdXfiDrP977QixsFYAjsWExVfxSoqJV",
      "fee": "1000000000",
      "validUntil": null,
      "nonce": "8"
    },
    "authorization": "2YFyASSiawWhHP16pdW2cvjST7951LdiYEBrz8hpomqJuSsoiQQMeU3oegkfM2MoHnur1MJJ4DiG8aRWFAqHdyPt7hxUe9K"
  },
  "accountUpdates": [
    {
      "body": {
        "publicKey": "B62qk8LrxcgNw7cGxgrNT2zdRdXfiDrP977QixsFYAjsWExVfxSoqJV",
        "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
        "balanceChange": { "magnitude": "1000000000", "sgn": "Negative" },
        "incrementNonce": true,
        "events": [],
        "sequenceEvents": [],
        "callData": "0",
        "callDepth": 0,
        "useFullCommitment": false,
        "caller": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf"
      }
    },
    {
      "body": {
        "publicKey": "B62qpRKsCw1ajngMUgPGi5baVkbCxpA8e6JTpRw5wiXf86CFs12GD2z",
        "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
        "balanceChange": { "magnitude": "0", "sgn": "Positive" },
        "incrementNonce": false,
        "events": [],
        "sequenceEvents": [],
        "callData": "27721005166194926617194650269806343668247885010559527474619238547652399684788",
        "callDepth": 0,
        "useFullCommitment": false,
        "caller": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf"
      }
    },
    {
      "body": {
        "publicKey": "B62qpRKsCw1ajngMUgPGi5baVkbCxpA8e6JTpRw5wiXf86CFs12GD2z",
        "tokenId": "x9MUjE7mQiDX1Ajo8wNehCDP2A2V8QauMRtYCyvy7jJ38vckff",
        "balanceChange": { "magnitude": "0", "sgn": "Positive" },
        "incrementNonce": false,
        "events": [],
        "sequenceEvents": [],
        "callData": "0",
        "callDepth": 1,
        "useFullCommitment": false,
        "caller": "x9MUjE7mQiDX1Ajo8wNehCDP2A2V8QauMRtYCyvy7jJ38vckff"
      }
    },
    {
      "body": {
        "publicKey": "B62qr9yya9KmQujHNTwdhE3tKeQXnxrVLkXqxU1ZusqiHCLok6cSDoa",
        "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
        "balanceChange": { "magnitude": "0", "sgn": "Positive" },
        "incrementNonce": false,
        "events": [],
        "sequenceEvents": [],
        "callData": "0",
        "callDepth": 0,
        "useFullCommitment": false,
        "caller": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf"
      }
    }
  ],
  "memo": "E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"
}

```

**Comment by mitschabaude** [comment]
Is this the caller issue? #431
