### ISSUE TITLE
`AccountUpdate.createSigned` throws an error in a transaction block

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#463]
# Description
In the current `main` branch of SnarkyJS, a possible regression was reintroduced. When using `AccountUpdate.createSigned` inside a transaction block, an error is thrown.

# Reproduce
```ts
import { isReady, Mina, AccountUpdate, shutdown } from 'snarkyjs';

await isReady;

let Local = Mina.LocalBlockchain();
Mina.setActiveInstance(Local);

let [{ privateKey: feePayerKey }] = Local.testAccounts;
let tx;

tx = await Mina.transaction({ feePayerKey }, () => {
  let feePayerUpdate = AccountUpdate.createSigned(feePayerKey);
});

shutdown();
```

## Stack Trace
```sh
/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7565
         throw err;
         ^

Error: Type "undefined" cannot be converted to a field element
    at raise_error (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:419858:44)
    at value$6 (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:419924:43)
    at caml_call_gen (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:2081:17)
    at /home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:3643:18
    at new eval (eval at caml_js_eval_string (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:3630:44), <anonymous>:4:26)
    at to_field_obj (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:419940:35)
    at /home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:420232:44
    at caml_call_gen (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:2081:17)
    at Function.<anonymous> (/home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:3643:18)
    at Function.Class.<computed> [as toFields] (file:///home/martin/Code/o1/mina/src/lib/snarky_js_bindings/snarkyjs/dist/node/snarky/proxy.js:21:62)
```

**Comment by MartinMinkov** [comment]
This is actually fixed in the latest commit on `main`

**Comment by mitschabaude** [comment]
nice :D
