### ISSUE TITLE
Better error handling of values pulled out from variables within the circuits

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/snarkyjs#478]
Having circuits (SC methods with `@method` decorators) with inappropriate usage of values pulled out from variables like:
- `Field.toString()`:

  ```typescript
  @method updateZkAppUri(uri: Field) {
    AccountUpdate.setValue(this.self.update.zkappUri, {
      data: uri.toString(),
      hash: Poseidon.hash([Field(this._zkAppUri)]),
    });
  }
  ```

- Or an undefined variables:

  ```typescript
  @method updateZkAppUri() {
    AccountUpdate.setValue(this.self.update.zkappUri, {
      data: thisIsAnUndefinedVar,
      hash: Poseidon.hash([Field(this._zkAppUri)]),
    });
  }
  ```

Results in error like the following:

```
[
  0,
  [ 248, MlBytes { t: 0, c: 'Jsoo_runtime.Error.Exn', l: 22 }, 233 ],
  Error: Can't evaluate prover code outside an as_prover block
      at failwith (src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:75548:50)
      at eval_as_prover (src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:143681:36)
      at read_var (src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:143684:36)
      at caml_call1 (src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7610:28)
      at to_string$54 (src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:419472:36)
      at src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:419519:52
      at caml_call_gen (src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:2081:17)
      at Object.toString (src/lib/snarky_js_bindings/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:3651:16)
      at E2eZkApp.updateZkAppUri (file:///src/E2eZkApp.js:37:23)
      at file:///src/lib/snarky_js_bindings/snarkyjs/src/lib/zkapp.ts:197:32
]
```

In which case actual cause with message is hidden within the output array.

**Comment by mitschabaude** [comment]
same as #489
