### ISSUE TITLE
Resolver error while running `npm test`

### ISSUE THREAD

**Issue by omrikiei** [o1-labs/snarkyjs#480]
Getting the following error while running `npm test` on a snarkyjs project
```
FAIL src/SSO.test.ts
  ● Test suite failed to run

    Cannot find module 'string:./snarky_js_chrome.bc.js' from 'node_modules/snarkyjs/dist/web/chrome_bindings/plonk_init.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:[32](https://github.com/omrikiei/zksso/actions/runs/3229143107/jobs/5286096466#step:4:33)4:11)
          at async Promise.all (index 0)
          at async Promise.all (index 0)
          at async Promise.all (index 0)
          at async Promise.all (index 2)
          at async Promise.all (index 1)
          at async Promise.all (index 0)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:[33](https://github.com/omrikiei/zksso/actions/runs/3229143107/jobs/5286096466#step:4:34)3:13)
      at runJest (node_modules/@jest/core/build/runJest.js:[40](https://github.com/omrikiei/zksso/actions/runs/3229143107/jobs/5286096466#step:4:41)4:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
```

Full code reference can be found [here](https://github.com/omrikiei/zksso)

**Comment by omrikiei** [comment]
Additional info by self troubleshooting - I printed the request and basedir for each import of something from snarkyjs that goes through the resolver - seems that this is related to the binding and usage of merkle_tree - where it is being referenced in web instead of in node by plonk_wasm.cjs:
![image](https://user-images.githubusercontent.com/6465556/195442407-3bf9366d-816c-48de-b842-0b2939a41d70.png)

**Comment by omrikiei** [comment]
OK found that the root cause are explicit imports in code and tests to web/lib instead of snarkyJS, feel free to close issue

**Comment by mitschabaude** [comment]
Thanks for debugging this, this could be very helpful troubleshooting info for others!
