### ISSUE TITLE
converting large 32 byte values to Field fails

### ISSUE THREAD

**Issue by marekyggdrasil** [o1-labs/snarkyjs#641]
example value

as hex `2452644332eebb5ea3174fcb1724b2b8826a600d4455b65e3a93609d58ae80c6`
as base58 `3SnYbQym9awSs3dTJVcDTJ5AVPXYgfca1u43Y7VgHPYy`
as bigInt `89785303736691784847086092688526102755694609368157008008048180906112472863268n`
as `number[]`

```
[
        36,  82, 100,  67, 50, 238, 187,  94,
        163,  23,  79, 203, 23,  36, 178, 184,
        130, 106,  96,  13, 68,  85, 182,  94,
        58, 147,  96, 157, 88, 174, 128, 198
    ]
```

## using fromBytes

```typescript
const data_field: Field = Field.fromBytes([
        36,  82, 100,  67, 50, 238, 187,  94,
        163,  23,  79, 203, 23,  36, 178, 184,
        130, 106,  96,  13, 68,  85, 182,  94,
        58, 147,  96, 157, 88, 174, 128, 198
    ]);
```

throws

```
    RuntimeError: unreachable

      at __rust_start_panic (wasm:/wasm/00e653d2:1:3312693)
      at rust_panic (wasm:/wasm/00e653d2:1:3307369)
      at std::panicking::rust_panic_with_hook::hb01d8793e567b040 (wasm:/wasm/00e653d2:1:3117430)
      at std::panicking::begin_panic_handler::{{closure}}::h60108af06f38ef3d (wasm:/wasm/00e653d2:1:3238474)
      at std::sys_common::backtrace::__rust_end_short_backtrace::h761906d06428c797 (wasm:/wasm/00e653d2:1:3303652)
      at rust_begin_unwind (wasm:/wasm/00e653d2:1:3285422)
      at core::panicking::panic_fmt::hffbf0f027a7fa92d (wasm:/wasm/00e653d2:1:3299960)
      at core::result::unwrap_failed::haf3f6481b8d95ef1 (wasm:/wasm/00e653d2:1:3264758)
      at <plonk_wasm::arkworks::pasta_fp::WasmPastaFp as wasm_bindgen::convert::traits::FromWasmAbi>::from_abi::h663aac302268cfb2 (wasm:/wasm/00e653d2:1:2752067)
      at caml_pasta_fp_to_bigint (wasm:/wasm/00e653d2:1:2261046)
```

## using Ledger

```typescript
const f: Field = Ledger.fieldOfBase58('3SnYbQym9awSs3dTJVcDTJ5AVPXYgfca1u43Y7VgHPYy');
```

throws

```
    thrown: Array [
      0,
      Array [
        248,
        MlBytes {
          "c": "Base58_check.Invalid_base58_checksum",
          "l": 36,
          "t": 0,
        },
        199,
      ],
      MlBytes {
        "c": "Token ID",
        "l": 8,
        "t": 0,
      },
    ]
```

## Using bigInt conversion

```typescript
function bytesToBigInt(bytes: Uint8Array) {
    let x = 0n;
    let bitPosition = 0n;
    for (let byte of bytes) {
        x += BigInt(byte) << bitPosition;
        bitPosition += 8n;
    }
    return x;
}

console.log(new Field(bytesToBigInt(data)));
```

where data is same array but as `Uint8Array`. This throws

```
    caml_pasta_fp_of_bigint

      54 |     console.log(v.toString());
      55 |     */
    > 56 |     console.log(new Field(bytesToBigInt(data)));
         |                 ^
      57 |     return [chunk_1, chunk_2, chunk_3, chunk_4];
      58 | }
      59 |

      at raise_error (node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:430864:44)
      at of_string_exn$0 (node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:430915:72)
      at value$6 (node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:430946:34)
      at caml_call_gen (node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:2081:17)
      at node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:3643:18
      at new eval (eval at caml_js_eval_string (node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:3630:44), <anonymous>:4:26)
      at new Class (node_modules/snarkyjs/src/snarky/proxy.js:11:14)
      at grinAddressToFields (src/helpers.ts:56:17)
      at Object.<anonymous> (src/helpers.test.ts:40:34)
```

**Comment by marekyggdrasil** [comment]
forgot to mention, I am using SnarkyJS `0.7.3`

**Comment by mitschabaude** [comment]
This is expected - the value you have is larger than the size of the field. With `Encoding.bytesToFields`, you can get two field elements.
