### ISSUE TITLE
`parseFetchedAccount` fails to fetch account details in case if SC was deployed

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/snarkyjs#725]
Checked with [Mina](https://github.com/MinaProtocol/mina/tree/test/berkeley-test-feb-10) and [SnarkyJS](https://github.com/MinaProtocol/mina/tree/merge-release-develop)

---

Account fetching fails on this one: https://github.com/o1-labs/snarkyjs/blob/52bd53245cbbf20cd553e1aba10fcfad14baa78b/src/lib/fetch.ts#L251

```shell
Fetching account details...
Something went wrong. Error: Type "undefined" cannot be converted to a field element
    at raise_error (/nix/store/bgdmsbs4z200hmhhspk4c8igmzfpg26n-js_of_ocaml-compiler-4.0.0/lib/ocaml/4.14.0/site-lib/js_of_ocaml-compiler/runtime/jsoo_runtime.ml:110:3)
    at t14 (/workspace_root/src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml:130:11)
    at caml_call_gen (/builtin/+stdlib.js:32:12)
    at /builtin/+jslib.js:252:14
    at new eval (eval at caml_js_eval_string (/builtin/+jslib.js:328:42), <anonymous>:4:26)
    at Class (file:///Users/shymkiv/projects/o1/mina/src/lib/snarky_js_bindings/snarkyjs/src/snarky/proxy.js:11:14)
    at parseFetchedAccount (file:///Users/shymkiv/projects/o1/mina/src/lib/snarky_js_bindings/snarkyjs/src/lib/fetch.ts:251:13)
    at fetchAccount (file:///Users/shymkiv/projects/o1/mina/src/lib/snarky_js_bindings/snarkyjs/src/lib/fetch.ts:73:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fetchAccountDetails (file:///Users/shymkiv/projects/o1/zkApps/e2e-zkapp/e2e-zkapp-ui/utils/ZkAppUtils.ts:325:22)
    at async file:///Users/shymkiv/projects/o1/zkApps/e2e-zkapp/e2e-zkapp-ui/routes/api.ts:157:20
Error: Type "undefined" cannot be converted to a field element
    at fetchAccountDetails (file:///Users/shymkiv/projects/o1/zkApps/e2e-zkapp/e2e-zkapp-ui/utils/ZkAppUtils.ts:332:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/shymkiv/projects/o1/zkApps/e2e-zkapp/e2e-zkapp-ui/routes/api.ts:157:20
```

**Comment by mitschabaude** [comment]
This includes adding a deriver for the account type, so it stays in sync

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @Trivo25
