### ISSUE TITLE
`Field.random` is circuit incompatible when used to update the contract set

### ISSUE THREAD

**Issue by Trivo25** [o1-labs/snarkyjs#790]
Updating the state of a smart contract (`this.x.set()`) with a value which originated from a computation that uses `Field.random()` or `Circuit.witness(Field, Field.random)` results in an unsatisfied constraint error

```ts
class SimpleZkapp extends SmartContract {
  @state(Field) x = State<Field>();

  @method update() {
    let x = this.x.get();
    this.x.assertEquals(x);

	// this below works fine
	// same for Circuit.witness(Field, Field.random)
    let a = Field.random();
	
	// this is the problem
    this.x.set(a);
  }
}
```

```
Error when proving SimpleZkapp.update()
Error: ( "Error: Constraint unsatisfied (unreduced):\
 \nChecked.Assert.equal\
 \nrule_main\
 \nstep_main\
 \n\
 \nConstraint:\
 \n((basic(Equal(Var 3)(Var 4484)))(annotation(Checked.Assert.equal)))\
 \nData:\
 \nEqual 20668686932801844266334470234757811891202773415958448182848973343511399700063 14031195169788612313117614081946252754914240362556182094100318148356441364122")
    at raise_error (/home/gregor/.opam/4.14.0/lib/js_of_ocaml-compiler/runtime/jsoo_runtime.ml:110:3)
    at log_and_raise_error_with_messa (/workspace_root/src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml:25:19)
    at null.<anonymous> (/workspace_root/src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml:388:19)
    at null.caml_call_gen (/builtin/+stdlib.js:32:12)
    at null.<anonymous> (/builtin/+jslib.js:252:14)
    at Object.eval [as assertEquals] (eval at caml_js_eval_string (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:3636:44), <anonymous>:4:20)
    at null.checkPublicInput (/home/trivo/Development/snarkyjs/src/lib/zkapp.ts:513:17)
    at null.<anonymous> (/home/trivo/Development/snarkyjs/src/lib/zkapp.ts:279:17)
    at null.runWith (/home/trivo/Development/snarkyjs/src/lib/global-context.ts:89:14)
    at Function.runWith (/home/trivo/Development/snarkyjs/src/lib/global-context.ts:43:9)
    at null.<anonymous> (/home/trivo/Development/snarkyjs/src/lib/zkapp.ts:186:54)
    at null.runWith (/home/trivo/Development/snarkyjs/src/lib/global-context.ts:89:14)
    at Function.runWith (/home/trivo/Development/snarkyjs/src/lib/global-context.ts:43:9)
    at SimpleZkapp.wrappedMethod (/home/trivo/Development/snarkyjs/src/lib/zkapp.ts:174:35)
    at null.<anonymous> (/home/trivo/Development/snarkyjs/src/lib/zkapp.ts:685:38)
    at null.main (/home/trivo/Development/snarkyjs/src/lib/proof_system.ts:472:5)
    at caml_call2 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7605:28)
    at null._gJX_ (/workspace_root/src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml:2010:30)
    at caml_call1 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7603:28)
    at null.<anonymous> (/workspace_root/src/lib/pickles/step_main.ml:292:15)
    at caml_call1 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7603:28)
    at null.with_label (/workspace_root/src/lib/snarky/src/base/snark0.ml:1243:15)
    at caml_call2 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7605:28)
    at null.<anonymous> (/workspace_root/src/lib/pickles/step_main.ml:291:11)
    at caml_call1 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7603:28)
    at null.with_label (/workspace_root/src/lib/snarky/src/base/snark0.ml:1243:15)
    at caml_call2 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7605:28)
    at null.main (/workspace_root/src/lib/pickles/step_main.ml:277:5)
    at null.caml_call_gen (/builtin/+stdlib.js:32:12)
    at null.caml_call_gen (/builtin/+stdlib.js:34:12)
    at caml_call2 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7605:37)
    at null.<anonymous> (/workspace_root/src/lib/pickles/step.ml:834:43)
    at caml_call1 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7603:28)
    at null.handle (/workspace_root/src/lib/snarky/src/base/snark0.ml:1227:15)
    at caml_call2 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7605:28)
    at null._iQf_ (/workspace_root/src/lib/pickles/step.ml:833:21)
    at null.caml_call_gen (/builtin/+stdlib.js:32:12)
    at null.<anonymous> (/builtin/+stdlib.js:42:14)
    at null.caml_call_gen (/builtin/+stdlib.js:28:22)
    at caml_call1 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7603:34)
    at null.mark_active (/workspace_root/src/lib/snarky/src/base/snark0.ml:1157:19)
    at null._pA8_ (/workspace_root/src/lib/snarky/src/base/snark0.ml:1278:52)
    at null.caml_call_gen (/builtin/+stdlib.js:32:12)
    at null.<anonymous> (/builtin/+stdlib.js:42:14)
    at null.caml_call_gen (/builtin/+stdlib.js:28:22)
    at caml_call1 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7603:34)
    at null.as_stateful (/workspace_root/src/lib/snarky/src/base/snark0.ml:737:15)
    at caml_call2 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7605:28)
    at handlers (/workspace_root/src/lib/snarky/src/base/runners.ml:82:22)
    at caml_call2 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7605:28)
    at null.<anonymous> (/workspace_root/src/lib/snarky/src/base/runners.ml:310:13)
    at caml_call4 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7609:28)
    at null.<anonymous> (/workspace_root/src/lib/snarky/src/base/runners.ml:278:34)
    at null.caml_call_gen (/builtin/+stdlib.js:32:12)
    at null.caml_call_gen (/builtin/+stdlib.js:34:12)
    at null.<anonymous> (/builtin/+stdlib.js:42:14)
    at null.caml_call_gen (/builtin/+stdlib.js:28:22)
    at caml_call5 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7611:46)
    at /home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:128517:38
    at null.caml_call_gen (/builtin/+stdlib.js:32:12)
    at null.caml_call_gen (/builtin/+stdlib.js:34:12)
    at caml_call6 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7615:16)
    at null.<anonymous> (/workspace_root/src/lib/snarky/src/base/snark0.ml:1278:19)
    at caml_call1 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7603:28)
    at null.finalize_is_running (/workspace_root/src/lib/snarky/src/base/snark0.ml:1257:15)
    at null.generate_witness_conv (/workspace_root/src/lib/snarky/src/base/snark0.ml:1277:7)
    at null.caml_call_gen (/builtin/+stdlib.js:32:12)
    at null.<anonymous> (/builtin/+stdlib.js:42:14)
    at null.caml_call_gen (/builtin/+stdlib.js:28:22)
    at null.caml_call_gen (/builtin/+stdlib.js:34:12)
    at null.<anonymous> (/builtin/+stdlib.js:42:14)
    at null.caml_call_gen (/builtin/+stdlib.js:28:22)
    at null.caml_call_gen (/builtin/+stdlib.js:34:12)
    at null.caml_call_gen (/builtin/+stdlib.js:34:12)
    at caml_call4 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7609:43)
    at null.<anonymous> (/workspace_root/src/lib/pickles/step.ml:807:7)
    at null.caml_call_gen (/builtin/+stdlib.js:32:12)
    at null.caml_call_gen (/builtin/+stdlib.js:34:12)
    at null.<anonymous> (/builtin/+stdlib.js:42:14)
    at null.caml_call_gen (/builtin/+stdlib.js:28:22)
    at caml_call10 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7631:16)
    at null.wrap (/workspace_root/src/lib/pickles/compile.ml:751:34)
    at caml_call2 (/home/trivo/Development/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7605:28)
    at Array.prove (/workspace_root/src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml:2279:7)
    at null.<anonymous> (/home/trivo/Development/snarkyjs/src/lib/account_update.ts:1927:38)
    at null.runWithAsync (/home/trivo/Development/snarkyjs/src/lib/global-context.ts:105:20)
    at Function.runWithAsync (/home/trivo/Development/snarkyjs/src/lib/global-context.ts:45:9)
    at null.<anonymous> (/home/trivo/Development/snarkyjs/src/lib/account_update.ts:1923:28)
    at null.runWithAsync (/home/trivo/Development/snarkyjs/src/lib/global-context.ts:105:20)
    at Function.runWithAsync (/home/trivo/Development/snarkyjs/src/lib/global-context.ts:45:9)
    at Object.run (/home/trivo/Development/snarkyjs/src/lib/proof_system.ts:611:27)
    at null.addProof (/home/trivo/Development/snarkyjs/src/lib/account_update.ts:1919:43)
    at null.addMissingProofs (/home/trivo/Development/snarkyjs/src/lib/account_update.ts:1955:48)
    at Object.prove (/home/trivo/Development/snarkyjs/src/lib/mina.ts:281:44)
    at file:///home/trivo/Development/snarkyjs/src/examples/simple_zkapp.tmp.js:64:10
```

**Comment by mitschabaude** [comment]
`Field.random()` can't work because you'd be encoding a different constant in the circuit than at compile time. I wonder about `Circuit.witness` though 🤔 
Can you reproduce this with other values returned from the witness callback?

**Comment by Trivo25** [comment]
I initially thought `Field.random` was already a witness, but seems like it isn't :D 
Here are some more clues:

- With `Circuit.witness(Field, Field.random)`, the verification key after compile never changes, as expected
- removing `this.x.set(a);`, while still invoking `Circuit.witness(Field, Field.random)`, "fixes" the error
- testing with `Circuit.witness(Field, () => Field(x))`, where `x` is either `0`, `Field.ORDER - 1n` or `Field.ORDER / 2n` works fine, as expected
- passing in a `Field.random` as method argument works `zkapp.update(Field.random());`, as expected
- this also doesn't work:
```ts
let a = Circuit.witness(Field, () => {
    let n = Math.ceil(Math.random() * 1000);
    return Field(n);
});

this.x.set(a);
```

after looking at the error message in detail, the assertion `checkPublicInput(publicInput, accountUpdate);` fails https://github.com/o1-labs/snarkyjs/blob/main/src/lib/zkapp.ts#L508

Some further research reveals that the account update constructed by the prover doesn't match the account update constructed by the transaction block - because the appState update doesn't match (the prover things the update is `x`, whereas its actually `y` https://github.com/o1-labs/snarkyjs/blob/main/src/lib/zkapp.ts#L235

Seems like its an known error

**Comment by mitschabaude** [comment]
Aaah now it's all clear to me! We run this twice and it creates different account updates with each run. Check out `memoizeWitness`, that's intended for this scenario

**Comment by Trivo25** [comment]
Awesome, thanks!
