### ISSUE TITLE
Building SnarkyJS

### ISSUE THREAD

**Issue by es92** [o1-labs/snarkyjs#913]
Having some issues when trying to build SnarkyJS from scratch, and then linking it into a project. What I'm doing:

```
$ git clone git@github.com:MinaProtocol/mina.git
$ git submodule update --init --recursive
$ cd src/lib/snarkyjs
$ npm install
$ npm run build:web
```

Then, from the ui folder of a svelte zkApp-cli project:

```
$ rm -rf node_modules/snarkyjs
$ npm link ~/gits/mina/src/lib/snarkyjs
```

npm run dev when loading the site on a browser yields:
```
* Internal server error: Failed to resolve entry for package "snarkyjs". The package may have incorrect main/module/exports specified in its package.json.
```

If I do

```
$ npm run build:node
```

Then instead npm run dev when loading the site on a browser yields:
```
ReferenceError: module is not defined
```

**Comment by ycryptx** [comment]
Facing the same issue

**Comment by mitschabaude** [comment]
Btw, you probably want to run both `npm run build` and `npm run build:web`

**Comment by es92** [comment]
> Does it work if you install local snarkyjs with `npm i ../path/to/snarkyjs`?

Unfortunately does not work, same set of errors @mitschabaude 

> Btw, you probably want to run both `npm run build` and `npm run build:web`

This has the same result as if I include `$ npm run build:node` (`ReferenceError: module is not defined`)

**Comment by ycryptx** [comment]
Can confirm that's true @es92

**Comment by shimkiv** [comment]
@es92 @ycryptx 
Since you're using `cd src/lib/snarkyjs` path I assume you're using Mina's latest `rampup` or `berkeley` branch. In which case before building SnarkyJS you need to update its sub-modules too. 
Then, `npm link` isn't it the [two-step process](https://docs.npmjs.com/cli/v9/commands/npm-link)? You first issue `npm link` being in SnarkyJS repo and then `npm link snarkyjs` being in zkApp repo.
So the steps might look like the following.

Mina repo:

```shell
git clone git@github.com:MinaProtocol/mina.git
cd mina/
git submodule update --init --recursive
cd src/lib/snarkyjs
git submodule sync
git submodule update --recursive --init
npm install
npm run build:node
npm run build:web
npm link
```

zkApp repo:

```shell
npm link snarkyjs
npm install
npm run dev
```

**Comment by shimkiv** [comment]
> isn't it the [two-step process](https://docs.npmjs.com/cli/v9/commands/npm-link)?

right, can be simplified into one command.

**Comment by es92** [comment]
Confirmed this has worked for me as well! I think the key was checking out the berkeley branch (tried / was trying develop and didn't seem to work with that).

Thanks!

**Comment by es92** [comment]
Nvm, unfortunately this didn't work. With the above I'm still getting 

`Internal server error: module is not defined`.

I think the issue could be, running `npm install` after `npm link snarkyjs` may be reinstalling the packaged remove version of snarkyjs, overriding the linked version?

If `npm install` is run first, same errors still show up

**Comment by ycryptx** [comment]
@es92 Did you manage to solve this?

**Comment by es92** [comment]
Nope, still stuck with above

**Comment by mitschabaude** [comment]
It works with published snarkyjs though, right? If yes, then you should be able to install from source by doing `npm pack` inside the snarkyjs repo and then installing the resulting tarball in your other project (and make sure to unlink snarkyjs). That should be equivalent to the install process that installing from npm gives you

**Comment by MartinMinkov** [comment]
I ran into the same issues related to `ReferenceError: module is not defined` when building locally and using that make inside a Svelte app.

I just wanted to confirm that using `npm pack` worked instead!

**Comment by marekyggdrasil** [comment]
The `npm pack` is working for me as well. Here's how I setup my local dev environment for SnarkyJS.

First of all, checking if it is same environment for all three directories (zkApp, SnarkyJS, smart contract)

```
$ nvm current
v18.16.0
```

In the SnarkyJS directory I run the steps provided by @shimkiv in https://github.com/o1-labs/snarkyjs/issues/913#issuecomment-1549075745 but instead of `npm link` I use `npm pack`

```
git submodule update --init --recursive
npm install
npm run build:node
npm run build:web
npm pack
```

this creates `/Users/marek/Development/open-source/snarkyjs/snarkyjs-0.10.1.tgz`
then in the smart contracts directory I run

```
rm -rf node_modules/
npm install /Users/marek/Development/open-source/snarkyjs/snarkyjs-0.10.1.tgz
npm run build
```

finally in the zkApp directory

```
rm -rf node_modules/
npm install /Users/marek/Development/open-source/snarkyjs/snarkyjs-0.10.1.tgz
npm install
npm run dev
```

Runs correctly.

If you are curious what happens if I use `npm link`, it also builds and starts but the zkApp crashes during compiling and my console gets flooded with following errors regarding undefined `navigator`

```
- ready started server on 0.0.0.0:3000, url: http://localhost:3000                                                                 [54/1846]
- event compiled client and server successfully in 6.2s (214 modules)                                                                       
- wait compiling...                                                                                                                         
- wait compiling /_error (client and server)...                                                                                             
- event compiled client and server successfully in 1620 ms (215 modules)                                                                    
ReferenceError: navigator is not defined                                                                                                    
    at getEfficientNumWorkers (webpack-internal:///../../../snarkyjs/dist/web/index.js:9131:17)                                             
    at async initSnarkyJS (webpack-internal:///../../../snarkyjs/dist/web/index.js:11328:20)                                                
    at async eval (webpack-internal:///../../../snarkyjs/dist/web/index.js:11447:1)                                                         
- warn Fast Refresh had to perform a full reload due to a runtime error.                                                                    
- wait compiling / (client and server)...                                                                                                   
- event compiled client and server successfully in 453 ms (235 modules)                                                                     
- error javascript/snarkyjs/dist/web/index.js (9057:0) @ getEfficientNumWorkers                                                             
- error Error [ReferenceError]: navigator is not defined                                                                                    
    at getEfficientNumWorkers (webpack-internal:///../../../snarkyjs/dist/web/index.js:9131:17)                                             
    at async initSnarkyJS (webpack-internal:///../../../snarkyjs/dist/web/index.js:11328:20)                                                
    at async eval (webpack-internal:///../../../snarkyjs/dist/web/index.js:11447:1) {                                                       
  digest: undefined                                                                                                                         
}                                                                                                                                           
  9055 | async function getEfficientNumWorkers() {                                                                                          
  9056 |   let gpuTier = await f();                                                                                                         
> 9057 |   let numCpus = navigator.hardwareConcurrency;                                                                                     
  9058 |   let gpuModel = gpuTier.gpu;                                                                                                      
  9059 |   var numWorkers = {                                                                                                               
  9060 |     "apple m1": 2,                                                                                                                 
ReferenceError: navigator is not defined                                                                                                    
    at getEfficientNumWorkers (webpack-internal:///../../../snarkyjs/dist/web/index.js:9131:17)                                             
    at async initSnarkyJS (webpack-internal:///../../../snarkyjs/dist/web/index.js:11328:20)                                                
    at async eval (webpack-internal:///../../../snarkyjs/dist/web/index.js:11447:1) {                                                       
  page: '/'                                                                                                                                 
}                                                                                                                                           
ReferenceError: navigator is not defined                                                                                                    
    at getEfficientNumWorkers (webpack-internal:///../../../snarkyjs/dist/web/index.js:9131:17)                                             
    at async initSnarkyJS (webpack-internal:///../../../snarkyjs/dist/web/index.js:11328:20)                                                
    at async eval (webpack-internal:///../../../snarkyjs/dist/web/index.js:11447:1) {                                                       
  page: '/'                                                                                                                                 
}                                                                                                                                           
ReferenceError: navigator is not defined                                                                                                    
    at getEfficientNumWorkers (webpack-internal:///../../../snarkyjs/dist/web/index.js:9131:17)                                             
    at async initSnarkyJS (webpack-internal:///../../../snarkyjs/dist/web/index.js:11328:20)                                                
    at async eval (webpack-internal:///../../../snarkyjs/dist/web/index.js:11447:1)                                                         
- warn Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload                           
- error javascript/snarkyjs/dist/web/index.js (9057:0) @ getEfficientNumWorkers                                                             
- error Error [ReferenceError]: navigator is not defined   
```

Insteresting that `navigator` seems recognized if `npm pack` is used but is undefined if `npm link` is used.

**Comment by mitschabaude** [comment]
Seems like, if `npm link` is used, sveltekit (or whatever tools it's using under the hood) tries to run the web build output in node at some point. I think this is incorrect behavior by the UI framework -- it should be fine to use `navigator` in a web library.

I think we can leave this unaddressed since there's a workaround
